# exported from PySB model 'model'

from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, EnergyPattern, Annotation, MultiState, Tag, ANY, WILD, as_complex_pattern

Model()

Monomer('FANCM', ['state'], {'state': ['False', 'True']})
Monomer('FAcore', ['state'], {'state': ['False', 'True']})
Monomer('FANCD2I', ['state'], {'state': ['False', 'True']})
Monomer('MUS81', ['state'], {'state': ['False', 'True']})
Monomer('FANCJBRCA1', ['state'], {'state': ['False', 'True']})
Monomer('XPF', ['state'], {'state': ['False', 'True']})
Monomer('FAN1', ['state'], {'state': ['False', 'True']})
Monomer('PCNATLS', ['state'], {'state': ['False', 'True']})
Monomer('MRN', ['state'], {'state': ['False', 'True']})
Monomer('BRCA1', ['state'], {'state': ['False', 'True']})
Monomer('ssDNARPA', ['state'], {'state': ['False', 'True']})
Monomer('FANCD1N', ['state'], {'state': ['False', 'True']})
Monomer('RAD51', ['state'], {'state': ['False', 'True']})
Monomer('HRR', ['state'], {'state': ['False', 'True']})
Monomer('USP1', ['state'], {'state': ['False', 'True']})
Monomer('KU', ['state'], {'state': ['False', 'True']})
Monomer('DNAPK', ['state'], {'state': ['False', 'True']})
Monomer('NHEJ', ['state'], {'state': ['False', 'True']})
Monomer('ATR', ['state'], {'state': ['False', 'True']})
Monomer('ATM', ['state'], {'state': ['False', 'True']})
Monomer('p53', ['state'], {'state': ['False', 'True']})
Monomer('CHK1', ['state'], {'state': ['False', 'True']})
Monomer('CHK2', ['state'], {'state': ['False', 'True']})
Monomer('H2AX', ['state'], {'state': ['False', 'True']})
Monomer('CHKREC', ['state'], {'state': ['False', 'True']})
Monomer('DSB', ['state'], {'state': ['False', 'True']})
Monomer('ADD', ['state'], {'state': ['False', 'True']})
Monomer('ICL', ['state'], {'state': ['False', 'True']})

Parameter('FANCM_False_init', 1.0)
Parameter('FANCM_True_init', 0.0)
Parameter('FAcore_False_init', 1.0)
Parameter('FAcore_True_init', 0.0)
Parameter('FANCD2I_False_init', 1.0)
Parameter('FANCD2I_True_init', 0.0)
Parameter('MUS81_False_init', 1.0)
Parameter('MUS81_True_init', 0.0)
Parameter('FANCJBRCA1_False_init', 1.0)
Parameter('FANCJBRCA1_True_init', 0.0)
Parameter('XPF_False_init', 1.0)
Parameter('XPF_True_init', 0.0)
Parameter('FAN1_False_init', 1.0)
Parameter('FAN1_True_init', 0.0)
Parameter('PCNATLS_False_init', 1.0)
Parameter('PCNATLS_True_init', 0.0)
Parameter('MRN_False_init', 1.0)
Parameter('MRN_True_init', 0.0)
Parameter('BRCA1_False_init', 1.0)
Parameter('BRCA1_True_init', 0.0)
Parameter('ssDNARPA_False_init', 1.0)
Parameter('ssDNARPA_True_init', 0.0)
Parameter('FANCD1N_False_init', 1.0)
Parameter('FANCD1N_True_init', 0.0)
Parameter('RAD51_False_init', 1.0)
Parameter('RAD51_True_init', 0.0)
Parameter('HRR_False_init', 1.0)
Parameter('HRR_True_init', 0.0)
Parameter('USP1_False_init', 1.0)
Parameter('USP1_True_init', 0.0)
Parameter('KU_False_init', 1.0)
Parameter('KU_True_init', 0.0)
Parameter('DNAPK_False_init', 1.0)
Parameter('DNAPK_True_init', 0.0)
Parameter('NHEJ_False_init', 1.0)
Parameter('NHEJ_True_init', 0.0)
Parameter('ATR_False_init', 1.0)
Parameter('ATR_True_init', 0.0)
Parameter('ATM_False_init', 1.0)
Parameter('ATM_True_init', 0.0)
Parameter('p53_False_init', 1.0)
Parameter('p53_True_init', 0.0)
Parameter('CHK1_False_init', 1.0)
Parameter('CHK1_True_init', 0.0)
Parameter('CHK2_False_init', 1.0)
Parameter('CHK2_True_init', 0.0)
Parameter('H2AX_False_init', 1.0)
Parameter('H2AX_True_init', 0.0)
Parameter('CHKREC_False_init', 1.0)
Parameter('CHKREC_True_init', 0.0)
Parameter('DSB_False_init', 0.0)
Parameter('DSB_True_init', 1.0)
Parameter('ADD_False_init', 1.0)
Parameter('ADD_True_init', 0.0)
Parameter('ICL_False_init', 1.0)
Parameter('ICL_True_init', 0.0)
Parameter('k_rate_ICL', 1.0)
Parameter('k_rate_FANCM', 1.0)
Parameter('k_rate_FAcore', 1.0)
Parameter('k_rate_FANCD2I', 1.0)
Parameter('k_rate_MUS81', 1.0)
Parameter('k_rate_FANCJBRCA1', 1.0)
Parameter('k_rate_XPF', 1.0)
Parameter('k_rate_FAN1', 1.0)
Parameter('k_rate_ADD', 1.0)
Parameter('k_rate_DSB', 1.0)
Parameter('k_rate_PCNATLS', 1.0)
Parameter('k_rate_MRN', 1.0)
Parameter('k_rate_BRCA1', 1.0)
Parameter('k_rate_ssDNARPA', 1.0)
Parameter('k_rate_FANCD1N', 1.0)
Parameter('k_rate_RAD51', 1.0)
Parameter('k_rate_HRR', 1.0)
Parameter('k_rate_USP1', 1.0)
Parameter('k_rate_KU', 1.0)
Parameter('k_rate_DNAPK', 1.0)
Parameter('k_rate_NHEJ', 1.0)
Parameter('k_rate_ATR', 1.0)
Parameter('k_rate_ATM', 1.0)
Parameter('k_rate_p53', 1.0)
Parameter('k_rate_CHK1', 1.0)
Parameter('k_rate_CHK2', 1.0)
Parameter('k_rate_H2AX', 1.0)
Parameter('k_rate_CHKREC', 1.0)

Observable('FANCM_False_obs', FANCM(state='False'))
Observable('FANCM_True_obs', FANCM(state='True'))
Observable('FAcore_False_obs', FAcore(state='False'))
Observable('FAcore_True_obs', FAcore(state='True'))
Observable('FANCD2I_False_obs', FANCD2I(state='False'))
Observable('FANCD2I_True_obs', FANCD2I(state='True'))
Observable('MUS81_False_obs', MUS81(state='False'))
Observable('MUS81_True_obs', MUS81(state='True'))
Observable('FANCJBRCA1_False_obs', FANCJBRCA1(state='False'))
Observable('FANCJBRCA1_True_obs', FANCJBRCA1(state='True'))
Observable('XPF_False_obs', XPF(state='False'))
Observable('XPF_True_obs', XPF(state='True'))
Observable('FAN1_False_obs', FAN1(state='False'))
Observable('FAN1_True_obs', FAN1(state='True'))
Observable('PCNATLS_False_obs', PCNATLS(state='False'))
Observable('PCNATLS_True_obs', PCNATLS(state='True'))
Observable('MRN_False_obs', MRN(state='False'))
Observable('MRN_True_obs', MRN(state='True'))
Observable('BRCA1_False_obs', BRCA1(state='False'))
Observable('BRCA1_True_obs', BRCA1(state='True'))
Observable('ssDNARPA_False_obs', ssDNARPA(state='False'))
Observable('ssDNARPA_True_obs', ssDNARPA(state='True'))
Observable('FANCD1N_False_obs', FANCD1N(state='False'))
Observable('FANCD1N_True_obs', FANCD1N(state='True'))
Observable('RAD51_False_obs', RAD51(state='False'))
Observable('RAD51_True_obs', RAD51(state='True'))
Observable('HRR_False_obs', HRR(state='False'))
Observable('HRR_True_obs', HRR(state='True'))
Observable('USP1_False_obs', USP1(state='False'))
Observable('USP1_True_obs', USP1(state='True'))
Observable('KU_False_obs', KU(state='False'))
Observable('KU_True_obs', KU(state='True'))
Observable('DNAPK_False_obs', DNAPK(state='False'))
Observable('DNAPK_True_obs', DNAPK(state='True'))
Observable('NHEJ_False_obs', NHEJ(state='False'))
Observable('NHEJ_True_obs', NHEJ(state='True'))
Observable('ATR_False_obs', ATR(state='False'))
Observable('ATR_True_obs', ATR(state='True'))
Observable('ATM_False_obs', ATM(state='False'))
Observable('ATM_True_obs', ATM(state='True'))
Observable('p53_False_obs', p53(state='False'))
Observable('p53_True_obs', p53(state='True'))
Observable('CHK1_False_obs', CHK1(state='False'))
Observable('CHK1_True_obs', CHK1(state='True'))
Observable('CHK2_False_obs', CHK2(state='False'))
Observable('CHK2_True_obs', CHK2(state='True'))
Observable('H2AX_False_obs', H2AX(state='False'))
Observable('H2AX_True_obs', H2AX(state='True'))
Observable('CHKREC_False_obs', CHKREC(state='False'))
Observable('CHKREC_True_obs', CHKREC(state='True'))
Observable('DSB_False_obs', DSB(state='False'))
Observable('DSB_True_obs', DSB(state='True'))
Observable('ADD_False_obs', ADD(state='False'))
Observable('ADD_True_obs', ADD(state='True'))
Observable('ICL_False_obs', ICL(state='False'))
Observable('ICL_True_obs', ICL(state='True'))

Rule('ICL_rule0', ICL(state='True') + DSB(state='True') >> ICL(state='False') + DSB(state='True'), k_rate_ICL)
Rule('FANCM_rule0', FANCM(state='True') + ICL(state='True') + CHKREC(state='True') >> FANCM(state='False') + ICL(state='True') + CHKREC(state='True'), k_rate_FANCM)
Rule('FANCM_rule1', FANCM(state='False') + ICL(state='True') + CHKREC(state='False') >> FANCM(state='True') + ICL(state='True') + CHKREC(state='False'), k_rate_FANCM)
Rule('FANCM_rule2', FANCM(state='True') + ICL(state='False') >> FANCM(state='False') + ICL(state='False'), k_rate_FANCM)
Rule('FAcore_rule0', FAcore(state='True') + FANCM(state='True') + CHKREC(state='True') >> FAcore(state='False') + FANCM(state='True') + CHKREC(state='True'), k_rate_FAcore)
Rule('FAcore_rule1', FAcore(state='False') + FANCM(state='True') + CHKREC(state='False') + ATR(state='True') >> FAcore(state='True') + FANCM(state='True') + CHKREC(state='False') + ATR(state='True'), k_rate_FAcore)
Rule('FAcore_rule2', FAcore(state='False') + FANCM(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='True') >> FAcore(state='True') + FANCM(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='True'), k_rate_FAcore)
Rule('FAcore_rule3', FAcore(state='True') + FANCM(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') >> FAcore(state='False') + FANCM(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='False'), k_rate_FAcore)
Rule('FAcore_rule4', FAcore(state='True') + FANCM(state='False') >> FAcore(state='False') + FANCM(state='False'), k_rate_FAcore)
Rule('FANCD2I_rule0', FANCD2I(state='True') + USP1(state='True') >> FANCD2I(state='False') + USP1(state='True'), k_rate_FANCD2I)
Rule('FANCD2I_rule1', FANCD2I(state='False') + USP1(state='False') + FAcore(state='True') + ATR(state='True') >> FANCD2I(state='True') + USP1(state='False') + FAcore(state='True') + ATR(state='True'), k_rate_FANCD2I)
Rule('FANCD2I_rule2', FANCD2I(state='False') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='True') >> FANCD2I(state='True') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='True'), k_rate_FANCD2I)
Rule('FANCD2I_rule3', FANCD2I(state='False') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='False') + H2AX(state='True') + DSB(state='True') >> FANCD2I(state='True') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='False') + H2AX(state='True') + DSB(state='True'), k_rate_FANCD2I)
Rule('FANCD2I_rule4', FANCD2I(state='True') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='False') + H2AX(state='True') + DSB(state='False') >> FANCD2I(state='False') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='False') + H2AX(state='True') + DSB(state='False'), k_rate_FANCD2I)
Rule('FANCD2I_rule5', FANCD2I(state='True') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='False') + H2AX(state='False') >> FANCD2I(state='False') + USP1(state='False') + FAcore(state='True') + ATR(state='False') + ATM(state='False') + H2AX(state='False'), k_rate_FANCD2I)
Rule('FANCD2I_rule6', FANCD2I(state='True') + USP1(state='False') + FAcore(state='False') >> FANCD2I(state='False') + USP1(state='False') + FAcore(state='False'), k_rate_FANCD2I)
Rule('MUS81_rule0', MUS81(state='False') + ICL(state='True') >> MUS81(state='True') + ICL(state='True'), k_rate_MUS81)
Rule('MUS81_rule1', MUS81(state='True') + ICL(state='False') >> MUS81(state='False') + ICL(state='False'), k_rate_MUS81)
Rule('FANCJBRCA1_rule0', FANCJBRCA1(state='False') + ICL(state='True') + ATM(state='True') >> FANCJBRCA1(state='True') + ICL(state='True') + ATM(state='True'), k_rate_FANCJBRCA1)
Rule('FANCJBRCA1_rule1', FANCJBRCA1(state='False') + ICL(state='True') + ATM(state='False') + ATR(state='True') >> FANCJBRCA1(state='True') + ICL(state='True') + ATM(state='False') + ATR(state='True'), k_rate_FANCJBRCA1)
Rule('FANCJBRCA1_rule2', FANCJBRCA1(state='True') + ICL(state='True') + ATM(state='False') + ATR(state='False') >> FANCJBRCA1(state='False') + ICL(state='True') + ATM(state='False') + ATR(state='False'), k_rate_FANCJBRCA1)
Rule('FANCJBRCA1_rule3', FANCJBRCA1(state='False') + ICL(state='False') + ssDNARPA(state='True') + ATM(state='True') >> FANCJBRCA1(state='True') + ICL(state='False') + ssDNARPA(state='True') + ATM(state='True'), k_rate_FANCJBRCA1)
Rule('FANCJBRCA1_rule4', FANCJBRCA1(state='False') + ICL(state='False') + ssDNARPA(state='True') + ATM(state='False') + ATR(state='True') >> FANCJBRCA1(state='True') + ICL(state='False') + ssDNARPA(state='True') + ATM(state='False') + ATR(state='True'), k_rate_FANCJBRCA1)
Rule('FANCJBRCA1_rule5', FANCJBRCA1(state='True') + ICL(state='False') + ssDNARPA(state='True') + ATM(state='False') + ATR(state='False') >> FANCJBRCA1(state='False') + ICL(state='False') + ssDNARPA(state='True') + ATM(state='False') + ATR(state='False'), k_rate_FANCJBRCA1)
Rule('FANCJBRCA1_rule6', FANCJBRCA1(state='True') + ICL(state='False') + ssDNARPA(state='False') >> FANCJBRCA1(state='False') + ICL(state='False') + ssDNARPA(state='False'), k_rate_FANCJBRCA1)
Rule('XPF_rule0', XPF(state='True') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='True') + FANCD2I(state='True') + FAN1(state='True') >> XPF(state='False') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='True') + FANCD2I(state='True') + FAN1(state='True'), k_rate_XPF)
Rule('XPF_rule1', XPF(state='False') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='True') + FANCD2I(state='True') + FAN1(state='False') >> XPF(state='True') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='True') + FANCD2I(state='True') + FAN1(state='False'), k_rate_XPF)
Rule('XPF_rule2', XPF(state='False') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='True') + FANCD2I(state='False') >> XPF(state='True') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='True') + FANCD2I(state='False'), k_rate_XPF)
Rule('XPF_rule3', XPF(state='False') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='False') >> XPF(state='True') + MUS81(state='True') + FANCM(state='True') + p53(state='True') + FAcore(state='False'), k_rate_XPF)
Rule('XPF_rule4', XPF(state='True') + MUS81(state='True') + FANCM(state='True') + p53(state='False') >> XPF(state='False') + MUS81(state='True') + FANCM(state='True') + p53(state='False'), k_rate_XPF)
Rule('XPF_rule5', XPF(state='False') + MUS81(state='True') + FANCM(state='False') >> XPF(state='True') + MUS81(state='True') + FANCM(state='False'), k_rate_XPF)
Rule('XPF_rule6', XPF(state='True') + MUS81(state='False') >> XPF(state='False') + MUS81(state='False'), k_rate_XPF)
Rule('FAN1_rule0', FAN1(state='False') + MUS81(state='True') + FANCD2I(state='True') >> FAN1(state='True') + MUS81(state='True') + FANCD2I(state='True'), k_rate_FAN1)
Rule('FAN1_rule1', FAN1(state='True') + MUS81(state='True') + FANCD2I(state='False') >> FAN1(state='False') + MUS81(state='True') + FANCD2I(state='False'), k_rate_FAN1)
Rule('FAN1_rule2', FAN1(state='True') + MUS81(state='False') >> FAN1(state='False') + MUS81(state='False'), k_rate_FAN1)
Rule('ADD_rule0', ADD(state='True') + PCNATLS(state='True') >> ADD(state='False') + PCNATLS(state='True'), k_rate_ADD)
Rule('ADD_rule1', ADD(state='False') + PCNATLS(state='False') + MUS81(state='True') + XPF(state='True') >> ADD(state='True') + PCNATLS(state='False') + MUS81(state='True') + XPF(state='True'), k_rate_ADD)
Rule('ADD_rule2', ADD(state='False') + PCNATLS(state='False') + MUS81(state='True') + XPF(state='False') + FAN1(state='True') >> ADD(state='True') + PCNATLS(state='False') + MUS81(state='True') + XPF(state='False') + FAN1(state='True'), k_rate_ADD)
Rule('DSB_rule0', DSB(state='True') + NHEJ(state='True') >> DSB(state='False') + NHEJ(state='True'), k_rate_DSB)
Rule('DSB_rule1', DSB(state='True') + NHEJ(state='False') + HRR(state='True') >> DSB(state='False') + NHEJ(state='False') + HRR(state='True'), k_rate_DSB)
Rule('DSB_rule2', DSB(state='False') + NHEJ(state='False') + HRR(state='False') + XPF(state='True') >> DSB(state='True') + NHEJ(state='False') + HRR(state='False') + XPF(state='True'), k_rate_DSB)
Rule('DSB_rule3', DSB(state='False') + NHEJ(state='False') + HRR(state='False') + XPF(state='False') + FAN1(state='True') >> DSB(state='True') + NHEJ(state='False') + HRR(state='False') + XPF(state='False') + FAN1(state='True'), k_rate_DSB)
Rule('PCNATLS_rule0', PCNATLS(state='True') + ADD(state='True') + USP1(state='True') >> PCNATLS(state='False') + ADD(state='True') + USP1(state='True'), k_rate_PCNATLS)
Rule('PCNATLS_rule1', PCNATLS(state='True') + ADD(state='True') + USP1(state='False') + FAN1(state='True') >> PCNATLS(state='False') + ADD(state='True') + USP1(state='False') + FAN1(state='True'), k_rate_PCNATLS)
Rule('PCNATLS_rule2', PCNATLS(state='False') + ADD(state='True') + USP1(state='False') + FAN1(state='False') >> PCNATLS(state='True') + ADD(state='True') + USP1(state='False') + FAN1(state='False'), k_rate_PCNATLS)
Rule('PCNATLS_rule3', PCNATLS(state='True') + ADD(state='False') >> PCNATLS(state='False') + ADD(state='False'), k_rate_PCNATLS)
Rule('MRN_rule0', MRN(state='True') + ATM(state='True') + CHKREC(state='True') >> MRN(state='False') + ATM(state='True') + CHKREC(state='True'), k_rate_MRN)
Rule('MRN_rule1', MRN(state='True') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='True') >> MRN(state='False') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='True'), k_rate_MRN)
Rule('MRN_rule2', MRN(state='True') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='False') + FANCD2I(state='True') + KU(state='True') >> MRN(state='False') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='False') + FANCD2I(state='True') + KU(state='True'), k_rate_MRN)
Rule('MRN_rule3', MRN(state='False') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='False') + FANCD2I(state='True') + KU(state='False') >> MRN(state='True') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='False') + FANCD2I(state='True') + KU(state='False'), k_rate_MRN)
Rule('MRN_rule4', MRN(state='False') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='False') + FANCD2I(state='False') >> MRN(state='True') + ATM(state='True') + CHKREC(state='False') + DSB(state='True') + RAD51(state='False') + FANCD2I(state='False'), k_rate_MRN)
Rule('MRN_rule5', MRN(state='True') + ATM(state='True') + CHKREC(state='False') + DSB(state='False') >> MRN(state='False') + ATM(state='True') + CHKREC(state='False') + DSB(state='False'), k_rate_MRN)
Rule('MRN_rule6', MRN(state='True') + ATM(state='False') >> MRN(state='False') + ATM(state='False'), k_rate_MRN)
Rule('BRCA1_rule0', BRCA1(state='True') + CHKREC(state='True') >> BRCA1(state='False') + CHKREC(state='True'), k_rate_BRCA1)
Rule('BRCA1_rule1', BRCA1(state='False') + CHKREC(state='False') + DSB(state='True') + CHK2(state='True') >> BRCA1(state='True') + CHKREC(state='False') + DSB(state='True') + CHK2(state='True'), k_rate_BRCA1)
Rule('BRCA1_rule2', BRCA1(state='False') + CHKREC(state='False') + DSB(state='True') + CHK2(state='False') + ATR(state='True') >> BRCA1(state='True') + CHKREC(state='False') + DSB(state='True') + CHK2(state='False') + ATR(state='True'), k_rate_BRCA1)
Rule('BRCA1_rule3', BRCA1(state='False') + CHKREC(state='False') + DSB(state='True') + CHK2(state='False') + ATR(state='False') + ATM(state='True') >> BRCA1(state='True') + CHKREC(state='False') + DSB(state='True') + CHK2(state='False') + ATR(state='False') + ATM(state='True'), k_rate_BRCA1)
Rule('BRCA1_rule4', BRCA1(state='True') + CHKREC(state='False') + DSB(state='True') + CHK2(state='False') + ATR(state='False') + ATM(state='False') >> BRCA1(state='False') + CHKREC(state='False') + DSB(state='True') + CHK2(state='False') + ATR(state='False') + ATM(state='False'), k_rate_BRCA1)
Rule('BRCA1_rule5', BRCA1(state='True') + CHKREC(state='False') + DSB(state='False') >> BRCA1(state='False') + CHKREC(state='False') + DSB(state='False'), k_rate_BRCA1)
Rule('ssDNARPA_rule0', ssDNARPA(state='True') + RAD51(state='True') >> ssDNARPA(state='False') + RAD51(state='True'), k_rate_ssDNARPA)
Rule('ssDNARPA_rule1', ssDNARPA(state='True') + RAD51(state='False') + DSB(state='True') + KU(state='True') >> ssDNARPA(state='False') + RAD51(state='False') + DSB(state='True') + KU(state='True'), k_rate_ssDNARPA)
Rule('ssDNARPA_rule2', ssDNARPA(state='False') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='True') >> ssDNARPA(state='True') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='True'), k_rate_ssDNARPA)
Rule('ssDNARPA_rule3', ssDNARPA(state='False') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='False') + FANCJBRCA1(state='True') + FANCD2I(state='True') >> ssDNARPA(state='True') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='False') + FANCJBRCA1(state='True') + FANCD2I(state='True'), k_rate_ssDNARPA)
Rule('ssDNARPA_rule4', ssDNARPA(state='True') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='False') + FANCJBRCA1(state='True') + FANCD2I(state='False') >> ssDNARPA(state='False') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='False') + FANCJBRCA1(state='True') + FANCD2I(state='False'), k_rate_ssDNARPA)
Rule('ssDNARPA_rule5', ssDNARPA(state='True') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='False') + FANCJBRCA1(state='False') >> ssDNARPA(state='False') + RAD51(state='False') + DSB(state='True') + KU(state='False') + MRN(state='False') + FANCJBRCA1(state='False'), k_rate_ssDNARPA)
Rule('ssDNARPA_rule6', ssDNARPA(state='True') + RAD51(state='False') + DSB(state='False') >> ssDNARPA(state='False') + RAD51(state='False') + DSB(state='False'), k_rate_ssDNARPA)
Rule('FANCD1N_rule0', FANCD1N(state='False') + ssDNARPA(state='True') + BRCA1(state='True') >> FANCD1N(state='True') + ssDNARPA(state='True') + BRCA1(state='True'), k_rate_FANCD1N)
Rule('FANCD1N_rule1', FANCD1N(state='True') + ssDNARPA(state='True') + BRCA1(state='False') + FANCD2I(state='True') + CHKREC(state='True') >> FANCD1N(state='False') + ssDNARPA(state='True') + BRCA1(state='False') + FANCD2I(state='True') + CHKREC(state='True'), k_rate_FANCD1N)
Rule('FANCD1N_rule2', FANCD1N(state='False') + ssDNARPA(state='True') + BRCA1(state='False') + FANCD2I(state='True') + CHKREC(state='False') >> FANCD1N(state='True') + ssDNARPA(state='True') + BRCA1(state='False') + FANCD2I(state='True') + CHKREC(state='False'), k_rate_FANCD1N)
Rule('FANCD1N_rule3', FANCD1N(state='True') + ssDNARPA(state='True') + BRCA1(state='False') + FANCD2I(state='False') >> FANCD1N(state='False') + ssDNARPA(state='True') + BRCA1(state='False') + FANCD2I(state='False'), k_rate_FANCD1N)
Rule('FANCD1N_rule4', FANCD1N(state='True') + ssDNARPA(state='False') >> FANCD1N(state='False') + ssDNARPA(state='False'), k_rate_FANCD1N)
Rule('RAD51_rule0', RAD51(state='True') + ssDNARPA(state='True') + FANCD1N(state='True') + CHKREC(state='True') >> RAD51(state='False') + ssDNARPA(state='True') + FANCD1N(state='True') + CHKREC(state='True'), k_rate_RAD51)
Rule('RAD51_rule1', RAD51(state='False') + ssDNARPA(state='True') + FANCD1N(state='True') + CHKREC(state='False') >> RAD51(state='True') + ssDNARPA(state='True') + FANCD1N(state='True') + CHKREC(state='False'), k_rate_RAD51)
Rule('RAD51_rule2', RAD51(state='True') + ssDNARPA(state='True') + FANCD1N(state='False') >> RAD51(state='False') + ssDNARPA(state='True') + FANCD1N(state='False'), k_rate_RAD51)
Rule('RAD51_rule3', RAD51(state='True') + ssDNARPA(state='False') >> RAD51(state='False') + ssDNARPA(state='False'), k_rate_RAD51)
Rule('HRR_rule0', HRR(state='True') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='True') + BRCA1(state='True') + CHKREC(state='True') >> HRR(state='False') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='True') + BRCA1(state='True') + CHKREC(state='True'), k_rate_HRR)
Rule('HRR_rule1', HRR(state='False') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='True') + BRCA1(state='True') + CHKREC(state='False') >> HRR(state='True') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='True') + BRCA1(state='True') + CHKREC(state='False'), k_rate_HRR)
Rule('HRR_rule2', HRR(state='True') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='True') + BRCA1(state='False') >> HRR(state='False') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='True') + BRCA1(state='False'), k_rate_HRR)
Rule('HRR_rule3', HRR(state='True') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='False') >> HRR(state='False') + DSB(state='True') + RAD51(state='True') + FANCD1N(state='False'), k_rate_HRR)
Rule('HRR_rule4', HRR(state='True') + DSB(state='True') + RAD51(state='False') >> HRR(state='False') + DSB(state='True') + RAD51(state='False'), k_rate_HRR)
Rule('HRR_rule5', HRR(state='True') + DSB(state='False') >> HRR(state='False') + DSB(state='False'), k_rate_HRR)
Rule('USP1_rule0', USP1(state='True') + FANCM(state='True') >> USP1(state='False') + FANCM(state='True'), k_rate_USP1)
Rule('USP1_rule1', USP1(state='False') + FANCM(state='False') + PCNATLS(state='True') >> USP1(state='True') + FANCM(state='False') + PCNATLS(state='True'), k_rate_USP1)
Rule('USP1_rule2', USP1(state='False') + FANCM(state='False') + PCNATLS(state='False') + FANCD1N(state='True') + FANCD2I(state='True') >> USP1(state='True') + FANCM(state='False') + PCNATLS(state='False') + FANCD1N(state='True') + FANCD2I(state='True'), k_rate_USP1)
Rule('USP1_rule3', USP1(state='True') + FANCM(state='False') + PCNATLS(state='False') + FANCD1N(state='True') + FANCD2I(state='False') >> USP1(state='False') + FANCM(state='False') + PCNATLS(state='False') + FANCD1N(state='True') + FANCD2I(state='False'), k_rate_USP1)
Rule('USP1_rule4', USP1(state='True') + FANCM(state='False') + PCNATLS(state='False') + FANCD1N(state='False') >> USP1(state='False') + FANCM(state='False') + PCNATLS(state='False') + FANCD1N(state='False'), k_rate_USP1)
Rule('KU_rule0', KU(state='True') + DSB(state='True') + MRN(state='True') >> KU(state='False') + DSB(state='True') + MRN(state='True'), k_rate_KU)
Rule('KU_rule1', KU(state='True') + DSB(state='True') + MRN(state='False') + FANCD2I(state='True') >> KU(state='False') + DSB(state='True') + MRN(state='False') + FANCD2I(state='True'), k_rate_KU)
Rule('KU_rule2', KU(state='True') + DSB(state='True') + MRN(state='False') + FANCD2I(state='False') + CHKREC(state='True') >> KU(state='False') + DSB(state='True') + MRN(state='False') + FANCD2I(state='False') + CHKREC(state='True'), k_rate_KU)
Rule('KU_rule3', KU(state='False') + DSB(state='True') + MRN(state='False') + FANCD2I(state='False') + CHKREC(state='False') >> KU(state='True') + DSB(state='True') + MRN(state='False') + FANCD2I(state='False') + CHKREC(state='False'), k_rate_KU)
Rule('KU_rule4', KU(state='True') + DSB(state='False') >> KU(state='False') + DSB(state='False'), k_rate_KU)
Rule('DNAPK_rule0', DNAPK(state='True') + DSB(state='True') + KU(state='True') + CHKREC(state='True') >> DNAPK(state='False') + DSB(state='True') + KU(state='True') + CHKREC(state='True'), k_rate_DNAPK)
Rule('DNAPK_rule1', DNAPK(state='False') + DSB(state='True') + KU(state='True') + CHKREC(state='False') >> DNAPK(state='True') + DSB(state='True') + KU(state='True') + CHKREC(state='False'), k_rate_DNAPK)
Rule('DNAPK_rule2', DNAPK(state='True') + DSB(state='True') + KU(state='False') >> DNAPK(state='False') + DSB(state='True') + KU(state='False'), k_rate_DNAPK)
Rule('DNAPK_rule3', DNAPK(state='True') + DSB(state='False') >> DNAPK(state='False') + DSB(state='False'), k_rate_DNAPK)
Rule('NHEJ_rule0', NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='True') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='True'), k_rate_NHEJ)
Rule('NHEJ_rule1', NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='True') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='True'), k_rate_NHEJ)
Rule('NHEJ_rule2', NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='False') >> NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule3', NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='False') >> NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule4', NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='False') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='True') + CHKREC(state='False') + XPF(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule5', NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='False') >> NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='True') + ATM(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule6', NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='False') >> NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='True') + ATR(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule7', NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='True') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='True'), k_rate_NHEJ)
Rule('NHEJ_rule8', NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='True') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='True'), k_rate_NHEJ)
Rule('NHEJ_rule9', NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='False') >> NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='True') + ssDNARPA(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule10', NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='False') >> NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='True') + FANCJBRCA1(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule11', NHEJ(state='True') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='False') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='True') + KU(state='False') + CHKREC(state='False') + XPF(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule12', NHEJ(state='True') + DSB(state='True') + DNAPK(state='False') >> NHEJ(state='False') + DSB(state='True') + DNAPK(state='False'), k_rate_NHEJ)
Rule('NHEJ_rule13', NHEJ(state='True') + DSB(state='False') >> NHEJ(state='False') + DSB(state='False'), k_rate_NHEJ)
Rule('ATR_rule0', ATR(state='True') + CHKREC(state='True') >> ATR(state='False') + CHKREC(state='True'), k_rate_ATR)
Rule('ATR_rule1', ATR(state='False') + CHKREC(state='False') + FANCM(state='True') >> ATR(state='True') + CHKREC(state='False') + FANCM(state='True'), k_rate_ATR)
Rule('ATR_rule2', ATR(state='False') + CHKREC(state='False') + FANCM(state='False') + ssDNARPA(state='True') >> ATR(state='True') + CHKREC(state='False') + FANCM(state='False') + ssDNARPA(state='True'), k_rate_ATR)
Rule('ATR_rule3', ATR(state='False') + CHKREC(state='False') + FANCM(state='False') + ssDNARPA(state='False') + ATM(state='True') >> ATR(state='True') + CHKREC(state='False') + FANCM(state='False') + ssDNARPA(state='False') + ATM(state='True'), k_rate_ATR)
Rule('ATR_rule4', ATR(state='True') + CHKREC(state='False') + FANCM(state='False') + ssDNARPA(state='False') + ATM(state='False') >> ATR(state='False') + CHKREC(state='False') + FANCM(state='False') + ssDNARPA(state='False') + ATM(state='False'), k_rate_ATR)
Rule('ATM_rule0', ATM(state='True') + CHKREC(state='True') >> ATM(state='False') + CHKREC(state='True'), k_rate_ATM)
Rule('ATM_rule1', ATM(state='False') + CHKREC(state='False') + ATR(state='True') >> ATM(state='True') + CHKREC(state='False') + ATR(state='True'), k_rate_ATM)
Rule('ATM_rule2', ATM(state='False') + CHKREC(state='False') + ATR(state='False') + DSB(state='True') >> ATM(state='True') + CHKREC(state='False') + ATR(state='False') + DSB(state='True'), k_rate_ATM)
Rule('ATM_rule3', ATM(state='True') + CHKREC(state='False') + ATR(state='False') + DSB(state='False') >> ATM(state='False') + CHKREC(state='False') + ATR(state='False') + DSB(state='False'), k_rate_ATM)
Rule('p53_rule0', p53(state='True') + CHKREC(state='True') >> p53(state='False') + CHKREC(state='True'), k_rate_p53)
Rule('p53_rule1', p53(state='False') + CHKREC(state='False') + DNAPK(state='True') >> p53(state='True') + CHKREC(state='False') + DNAPK(state='True'), k_rate_p53)
Rule('p53_rule2', p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='True') >> p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='True'), k_rate_p53)
Rule('p53_rule3', p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='False') + ATM(state='True') + CHK2(state='True') >> p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='False') + ATM(state='True') + CHK2(state='True'), k_rate_p53)
Rule('p53_rule4', p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='False') + ATM(state='True') + CHK2(state='False') >> p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='False') + ATM(state='True') + CHK2(state='False'), k_rate_p53)
Rule('p53_rule5', p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='False') + ATM(state='False') >> p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='True') + ATR(state='False') + ATM(state='False'), k_rate_p53)
Rule('p53_rule6', p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='False') + ATM(state='True') + CHK2(state='True') >> p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='False') + ATM(state='True') + CHK2(state='True'), k_rate_p53)
Rule('p53_rule7', p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='False') + ATM(state='True') + CHK2(state='False') >> p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='False') + ATM(state='True') + CHK2(state='False'), k_rate_p53)
Rule('p53_rule8', p53(state='True') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='False') + ATM(state='False') >> p53(state='False') + CHKREC(state='False') + DNAPK(state='False') + CHK1(state='False') + ATM(state='False'), k_rate_p53)
Rule('CHK1_rule0', CHK1(state='True') + CHKREC(state='True') >> CHK1(state='False') + CHKREC(state='True'), k_rate_CHK1)
Rule('CHK1_rule1', CHK1(state='False') + CHKREC(state='False') + ATR(state='True') >> CHK1(state='True') + CHKREC(state='False') + ATR(state='True'), k_rate_CHK1)
Rule('CHK1_rule2', CHK1(state='False') + CHKREC(state='False') + ATR(state='False') + ATM(state='True') >> CHK1(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='True'), k_rate_CHK1)
Rule('CHK1_rule3', CHK1(state='False') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='True') >> CHK1(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='True'), k_rate_CHK1)
Rule('CHK1_rule4', CHK1(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='False') >> CHK1(state='False') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='False'), k_rate_CHK1)
Rule('CHK2_rule0', CHK2(state='True') + CHKREC(state='True') >> CHK2(state='False') + CHKREC(state='True'), k_rate_CHK2)
Rule('CHK2_rule1', CHK2(state='False') + CHKREC(state='False') + ATR(state='True') >> CHK2(state='True') + CHKREC(state='False') + ATR(state='True'), k_rate_CHK2)
Rule('CHK2_rule2', CHK2(state='False') + CHKREC(state='False') + ATR(state='False') + ATM(state='True') >> CHK2(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='True'), k_rate_CHK2)
Rule('CHK2_rule3', CHK2(state='False') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='True') >> CHK2(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='True'), k_rate_CHK2)
Rule('CHK2_rule4', CHK2(state='True') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='False') >> CHK2(state='False') + CHKREC(state='False') + ATR(state='False') + ATM(state='False') + DNAPK(state='False'), k_rate_CHK2)
Rule('H2AX_rule0', H2AX(state='True') + CHKREC(state='True') >> H2AX(state='False') + CHKREC(state='True'), k_rate_H2AX)
Rule('H2AX_rule1', H2AX(state='False') + CHKREC(state='False') + DSB(state='True') + ATR(state='True') >> H2AX(state='True') + CHKREC(state='False') + DSB(state='True') + ATR(state='True'), k_rate_H2AX)
Rule('H2AX_rule2', H2AX(state='False') + CHKREC(state='False') + DSB(state='True') + ATR(state='False') + DNAPK(state='True') >> H2AX(state='True') + CHKREC(state='False') + DSB(state='True') + ATR(state='False') + DNAPK(state='True'), k_rate_H2AX)
Rule('H2AX_rule3', H2AX(state='False') + CHKREC(state='False') + DSB(state='True') + ATR(state='False') + DNAPK(state='False') + ATM(state='True') >> H2AX(state='True') + CHKREC(state='False') + DSB(state='True') + ATR(state='False') + DNAPK(state='False') + ATM(state='True'), k_rate_H2AX)
Rule('H2AX_rule4', H2AX(state='True') + CHKREC(state='False') + DSB(state='True') + ATR(state='False') + DNAPK(state='False') + ATM(state='False') >> H2AX(state='False') + CHKREC(state='False') + DSB(state='True') + ATR(state='False') + DNAPK(state='False') + ATM(state='False'), k_rate_H2AX)
Rule('H2AX_rule5', H2AX(state='True') + CHKREC(state='False') + DSB(state='False') >> H2AX(state='False') + CHKREC(state='False') + DSB(state='False'), k_rate_H2AX)
Rule('CHKREC_rule0', CHKREC(state='True') + DSB(state='True') >> CHKREC(state='False') + DSB(state='True'), k_rate_CHKREC)
Rule('CHKREC_rule1', CHKREC(state='False') + DSB(state='False') + NHEJ(state='True') >> CHKREC(state='True') + DSB(state='False') + NHEJ(state='True'), k_rate_CHKREC)
Rule('CHKREC_rule2', CHKREC(state='False') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='True') >> CHKREC(state='True') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='True'), k_rate_CHKREC)
Rule('CHKREC_rule3', CHKREC(state='False') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='True') >> CHKREC(state='True') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='True'), k_rate_CHKREC)
Rule('CHKREC_rule4', CHKREC(state='True') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='True') >> CHKREC(state='False') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='True'), k_rate_CHKREC)
Rule('CHKREC_rule5', CHKREC(state='True') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='False') + ICL(state='True') >> CHKREC(state='False') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='False') + ICL(state='True'), k_rate_CHKREC)
Rule('CHKREC_rule6', CHKREC(state='True') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='False') + ICL(state='False') >> CHKREC(state='False') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='False') + ICL(state='False'), k_rate_CHKREC)
Rule('CHKREC_rule7', CHKREC(state='False') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='False') + ICL(state='False') >> CHKREC(state='True') + DSB(state='False') + NHEJ(state='False') + PCNATLS(state='False') + HRR(state='False') + ADD(state='False') + ICL(state='False'), k_rate_CHKREC)

Initial(FANCM(state='False'), FANCM_False_init)
Initial(FANCM(state='True'), FANCM_True_init)
Initial(FAcore(state='False'), FAcore_False_init)
Initial(FAcore(state='True'), FAcore_True_init)
Initial(FANCD2I(state='False'), FANCD2I_False_init)
Initial(FANCD2I(state='True'), FANCD2I_True_init)
Initial(MUS81(state='False'), MUS81_False_init)
Initial(MUS81(state='True'), MUS81_True_init)
Initial(FANCJBRCA1(state='False'), FANCJBRCA1_False_init)
Initial(FANCJBRCA1(state='True'), FANCJBRCA1_True_init)
Initial(XPF(state='False'), XPF_False_init)
Initial(XPF(state='True'), XPF_True_init)
Initial(FAN1(state='False'), FAN1_False_init)
Initial(FAN1(state='True'), FAN1_True_init)
Initial(PCNATLS(state='False'), PCNATLS_False_init)
Initial(PCNATLS(state='True'), PCNATLS_True_init)
Initial(MRN(state='False'), MRN_False_init)
Initial(MRN(state='True'), MRN_True_init)
Initial(BRCA1(state='False'), BRCA1_False_init)
Initial(BRCA1(state='True'), BRCA1_True_init)
Initial(ssDNARPA(state='False'), ssDNARPA_False_init)
Initial(ssDNARPA(state='True'), ssDNARPA_True_init)
Initial(FANCD1N(state='False'), FANCD1N_False_init)
Initial(FANCD1N(state='True'), FANCD1N_True_init)
Initial(RAD51(state='False'), RAD51_False_init)
Initial(RAD51(state='True'), RAD51_True_init)
Initial(HRR(state='False'), HRR_False_init)
Initial(HRR(state='True'), HRR_True_init)
Initial(USP1(state='False'), USP1_False_init)
Initial(USP1(state='True'), USP1_True_init)
Initial(KU(state='False'), KU_False_init)
Initial(KU(state='True'), KU_True_init)
Initial(DNAPK(state='False'), DNAPK_False_init)
Initial(DNAPK(state='True'), DNAPK_True_init)
Initial(NHEJ(state='False'), NHEJ_False_init)
Initial(NHEJ(state='True'), NHEJ_True_init)
Initial(ATR(state='False'), ATR_False_init)
Initial(ATR(state='True'), ATR_True_init)
Initial(ATM(state='False'), ATM_False_init)
Initial(ATM(state='True'), ATM_True_init)
Initial(p53(state='False'), p53_False_init)
Initial(p53(state='True'), p53_True_init)
Initial(CHK1(state='False'), CHK1_False_init)
Initial(CHK1(state='True'), CHK1_True_init)
Initial(CHK2(state='False'), CHK2_False_init)
Initial(CHK2(state='True'), CHK2_True_init)
Initial(H2AX(state='False'), H2AX_False_init)
Initial(H2AX(state='True'), H2AX_True_init)
Initial(CHKREC(state='False'), CHKREC_False_init)
Initial(CHKREC(state='True'), CHKREC_True_init)
Initial(DSB(state='False'), DSB_False_init)
Initial(DSB(state='True'), DSB_True_init)
Initial(ADD(state='False'), ADD_False_init)
Initial(ADD(state='True'), ADD_True_init)
Initial(ICL(state='False'), ICL_False_init)
Initial(ICL(state='True'), ICL_True_init)

